### ISSUE TITLE
Plants proc allergies through hardsuits and internals

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#102]
#### Brief description of the bug

Plants proc allergy reactions while wearing hardsuits (Tested on medical rig), and on internals. Wearing a gas mask protects you regardless of internals? (Needs testing)
Wearing gloves does not protect you from harvesting plants. (Might need to be a specific glove type?)

Allergies should respect if you're on internals, and if you're wearing full body protection.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/42ffbd71c555c8ba439f86c39cb4c754e4b914ef
