### ISSUE TITLE
Allow machines to start upgraded via mapping

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#109]
#### Brief description of the feature

Machines can be upgraded in-game by either partially deconstructing and adding upgraded parts, or using a rapid part exchanger, loaded with the correct upgrade parts.
Machines should be able to be upgraded on init, by mapping in the correct upgraded parts, then the machine checking the turf for any components placed on them, and replacing their initialized parts with the upgraded version as it would be if they were manually upgraded

**Comment by Willburd** [comment]
Initially resolved in https://github.com/Willburd/CHOMPost21/commit/bbd97ad970f7c6eaac15fbf7b92395734b7a0e00
