### ISSUE TITLE
[MAP] Add a mounted gas analyzer to the phoronics cooling loop

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#114]
#### Brief description of the bug
The piping in the phoronics cooling loop needs a gas analyzer mounted on it, so once you drain a tank into the cooling loop you can check the temperature before piping it back out.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/87d2dd8465da9222da088e6627c77afab4c4715b
