### ISSUE TITLE
✨Firing a wielded weapon with lightweight knocks you prone and sends you back 1-2 tiles

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#120]
#### Brief description of the feature

Some guns must be wielded (two handed), these weapons are very lorge in caliber.
With the lightweight trait, you get knocked over when people bump into you on harm intent.
Combining the two will be funny as hell. Firing a wielded weapon, with the lightweight trait, knocks you back and knocks you prone.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/28188cc842faa59a91a2c7bde616e59c15a0627e
