### ISSUE TITLE
Item lockers should be able to re-store pulled out items

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#121]
#### Brief description of the bug

Item lockers ( obj/machinery/item_bank ) cannot accept items taken from them that shift.
While their lack of ability to store every item is fine, and not being able to store container contents is good, the fact you can't put away an item you've saved, while only being able to save one item, is silly and likely only implemented for "balance."
Items should be able to be saved after being taken out that round

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/f45028d065570dd1d2ded84baffa93571142124b
