### ISSUE TITLE
COMSIG_OBSERVER_TURF_ENTERED signals cause a leak with effects crossing

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#124]
#### Brief description of the bug

Emitters are memory leaking again, likely by crossing the on-step on shield generator fields.
My theory is chomp modified the files and reverted the fixes we had prior, undoing them.

**Comment by Willburd** [comment]
It's not the emitter shields, it's other objects that register a a turfenter signal

**Comment by Willburd** [comment]
Related https://github.com/Willburd/CHOMPost21/issues/56

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/5dba4d42693bd55b51631348087005f7f7b9965f
