### ISSUE TITLE
CPR nonfunctional on people dead but under 200 total damage

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#125]
#### Brief description of the bug

Crewmembers that are CPR'd from hyperdead to under 200 damage stop having it work on them, only allowing you to "shake to wake the person up." despite them being still dead. You shouldn't shake people awake if they're flagged as dead, or certain medications and such can't function, if you want to do specialized treatment right at the end before you completely un-fuck the person.

Alternative fix: machine similar to feeders and IV stands that just slowly "CPR's" you automatically but slowly.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/9349d10fc26ab2f6d9a936f80ebb7a369b862db7
