### ISSUE TITLE
Medical comms bleeding into other people's comms inconsistently

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#126]
#### Brief description of the bug

Medical comms are bleeding into people's headsets(?) inconsistently, does not happen during round start.
Potential causes:
- Power failure causing bad reset in telecoms.
- Chomp disabled line of sight checks on radio/device audio, and it's possible they're hearing radios set to medical via EMP or something else and hearing it through the walls.
- Something in T-coms is misconfigured as a slow bleed? Potentially a minor event?

**Comment by Willburd** [comment]
Reversion experiment https://github.com/Willburd/CHOMPost21/commit/f46ddc8ea39a19ac6c341d043e911c3c91471703
