### ISSUE TITLE
✨New landmines

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#127]
#### Brief description of the feature

-Landmine that when stepped on, adds spacelube in a 5x5-7x7 square centered on itself
-Landmine that when stepped on, does the same as above but with the slug sticky goo stuff.
-Landmine that spawns 10-15 spiderlings, also spawns spiderwebs to trap you?
-Bluespace landmine. Randomly teleports you on the station, similar to wormholes/bluespace tomatoes.
-Landmine that detonates into party blower and confetti. Rare chance to cause heart damage?

-Add mantraps and pitcherplants to step_traps?

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/baaf5453a1831edef932e3b76bbcb6b32ca0ef09
