### ISSUE TITLE
Ore and mob spawn issues on Muriki

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#14]
#### Brief description of the bug
Ore generation is too high/valuable and should be nerfed again to pre-chomp move.

Multiple mobs are regularly spawning in maintenance, which is fine.. but need to be curtailed and pruned to mobs that make sense on Muriki - New mobs that remain may need to be given enzyme immunity, those that don't remain shouldn't have it

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/9d43cc9ea14041a6e600aa74737afce5c5b6145e
