### ISSUE TITLE
Events not respecting Z-level bars

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#15]
#### Brief description of the bug

Events that had previously been flagged for reclamation yard, or planet surface only, no longer respect which map they're on. Likely due to an issue with what z-levels are currently flagged as "station Z-levels"
Noticed with space dust impacting the surface, and solar grubs spawning on the reclamation yard (which I guess isn't.. terrible? but hints at spiders spawning there, and meteors striking the surface)

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/e445c59eb9e957f061f9355bb500cd9463012998
