### ISSUE TITLE
Body cameras show ghosts, but normal cameras don't

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#173]
This is a bug that needs to become a feature.
Noticed when Zeeshi was able to spot me admeming as a ghost while watching a body camera of an officer, but so far we've been unable to make ghosts show up on security cameras and borg vision. We should look into what caused this bug on body cameras, and use it to improve borg vision and security cameras.

**Comment by Willburd** [comment]
Unable to replicate
