### ISSUE TITLE
Translators are nearly nonfunctional

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#176]
#### Brief description of the bug

Translators, both hand held and ear worn, do not work if anything is heard through any radio, muffled by a stomach, or literally anything but having direct line of sight to the person renders them nonfunctional.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/5e687804f085f34a685f5b15d0da830e7030758b
