### ISSUE TITLE
✨Xenoarch ideas

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#194]
#### Brief description of the feature

New xenoarch artifacts that could rarely be found.. maybe one that just creates a shitload of filth. Potentially if overexcited just floods station areas with tons of filth and trash. The janitor's nightmare.

**Comment by Willburd** [comment]
Resolved as a new disposals event instead https://github.com/Willburd/CHOMPost21/commit/ba6925504c27d56868503c295bd7daf9fa74b792
