### ISSUE TITLE
[GENERAL] Hoists cannot be dismounted if your sprite covers the hook

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#196]
Hoists are dismounted by clicking and dragging the hook onto a nearby turf. But if your sprite obscures this, you can't drag the hook from the alt-click menu onto the turf to dismount you.
This should either by fixed by allowing the hook itself to be rotated post-mounting (the best solution), by allowing the hook to be dragged from the alt-click menu, or clicking and dragging THE PERSON to the tile to unmount them.

**Comment by IgnusVam** [comment]
This issue is quickly turning into a straight up refactor of hoists, because they're coded so badly. So, we'll see what happens with this.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/924db9dcf06b6679d7d2ff9d31863f0e8c7c6e34
