### ISSUE TITLE
[GENERAL] Tazers are insane against mobs

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#197]
Tazers cause hallucination damage almost entirely, and a rather sizable chunk of it. This is necessary for them to be a nonlethal weapon and not suck. However, Simplemobs are OLD AS CRAP and don't actually have any checks for halloss, so they take it all as normal damage.
This means that with most mobs having armor against bullets, spears, slashing, etc.. none of them at all have armor against tazers, so it does full damage on targets intended to be armored, killing them very quickly.
This is due to simplemobs being older than hallucination damage, and IS actually a long standing bug that nobody's fixed because nobody realizes it's a bug.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/d9a852992869c1ef7e42a295457d9c18aefe560f
