### ISSUE TITLE
✨Superfart Flamethrower

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#201]
#### Brief description of the feature

Overview of the feature:
-New secret interaction with an ignited source (Match, lighter, lit welder, etc)
-Target lower body on help intent.
-On click, it checks if the target (you or another creature) has the superfart gene, if they do. Check the direction they're facing, then send off a flamethrower burst in the opposite direction.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/333cffc535f94b19600fd8eafe2ef51d2b938e55
