### ISSUE TITLE
✨Fart powered rolling chairs

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#202]
#### Brief description of the feature

If you superfart while buckled onto a rolling chair, or in zero-G, it fucking LAUNCHES you. Twice the speed and distance of a fire extinguisher.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/333cffc535f94b19600fd8eafe2ef51d2b938e55
