### ISSUE TITLE
[GENERAL] Attempting to build lattices in open space in the terraformer doesn't create lattices

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#205]
Attempting to build latticework in the terraformer on open spaces just resets the turf to a flesh floor tile. Likely pulling from default turf?

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/de4af68575806f3341eb287e1031d596cb8e69cd
