### ISSUE TITLE
✨Moss

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#207]
#### Brief description of the feature

Thinking it could be a "peaceful" version of space vines that very slowly spreads and grows in the area. Possibly on a high enough layer it can grow over landmines and traps to better hide them.
-Tie in with fire code: Moss can burn REALLY EASILY and great for causing utterly insane fires throughout maintenance.
-Should be able to be harvested for some kind of food item, A-la the joke of "Sorting moss"

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/2f4b508ad353a0925a038a34158301a119cc6f40
