### ISSUE TITLE
✨Stationary, permanent shadekin disruptor

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#210]
#### Brief description of the feature

Take the code from Bluespace crystals (obj/item/weapon/bluespace_crystal ?), that forces shadekin into realspace to make a proper structure one that has a much bigger radius, for protecting HIGHLY sensitive areas, like the terraformer, armory, stuff like that.
If this is a known thing, E-Shui would have weaponized it. (Give it neat "vox-like" designs because where do you think they got it from~?)

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/2490e254817db11a8370a8383ccfc00f473afd34
