### ISSUE TITLE
✨Fire code Rework

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#215]
#### Brief description of the feature

Fire that is dangerous and spreadable.
- [x] Give every turf and item a flammability
- [x] If a fire starts, it slowly burns away and damages anything with flammability above a threshold, items that are flammable get burned and reduced to ash same as clicking on a paper with a lighter.
- [x] Fires will be the actual on-turf fire, not a full room gas flame like phoron fires.
- [x] Ignites and explodes gas tanks regardless of the gas inside being flammable
- [x] Fire fills a room with Co2
- [x] Kitchen fires, APC sparks, lights breaking, etc, all suddenly become a lot more dangerous~
- [x] Fire extinguishers and firesuits actually get a use for once

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/pull/389
