### ISSUE TITLE
✨Candy bowl item

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#218]
#### Brief description of the feature

Literally only desired because the current candy bowl item is a trash item, and with trash persistence it's slowly duplicating itself in the room.
Just a cute decorative item, possibly even functionless, just for placing candies in, in the medical lobby.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/ae327c04b43fdda7d13e130468f65d22d011e99a
