### ISSUE TITLE
[GENERAL] Players in VR with lonelyness(?) randomly turn into mobs and can dephase as some into ghosts.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#222]
#### Brief description of the bug

Players when killed in VR, are turned into a ghost, when they should ejected from VR with the damage they had sustained mirrored into hallucination pain.

**Comment by Willburd** [comment]
related to vr_mob_tf_options ?

**Comment by Willburd** [comment]
Appears to be resolved by upstream?
