### ISSUE TITLE
[GENERAL] Cryo pods annoucning stowaway departure.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#223]
#### Brief description of the bug

Stowaways are having their departure announced when DC'ing via cryopod, cryopods were meant to sneakily put them away to keep the station on edge, and "they're not crew" so it wouldn't announce them

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/a62f8e66bedd4f28c4846edeae013f5e41531b88
