### ISSUE TITLE
Any inhabited body prevents the autosleever from firing

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#23]
#### Brief description of the bug

If your ID is thrown into trash and sorted to the autosleever, if you're inhabiting ANY other body, such as a mouse, jil, maint pred, etc, it will automatically fail the resleeve attempt, thinking you're already alive.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/7e175d3343c202eb3169e1f8cfe73eb0fa8e3616
