### ISSUE TITLE
[GENERAL] Red armory door doesn't change its access on alert levels

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#239]
#### Brief description of the bug

The door obj/machinery/door/airlock/highsecurity/red does not update its access based off alert level as it should. It should drop its req_oneaccess to a different variable on codes blue, red, and delta. It currently does not.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/af4cae29e736b84ef7784a691c5867be5edf1192
