### ISSUE TITLE
[Investigate] CPR behaving strangely and not working often.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#24]
#### Brief description of the bug

There appears to be a bug when attempting to perform CPR on crewmates that are either critically dead, or only minorly dead. Results inconclusive due to other bug noting inconsistent results with hand analyzers vs body scanners.

**Comment by Willburd** [comment]
Inconsistent behavior is due to separate wounds caused by burns. Separate burn wound healing must be done.
