### ISSUE TITLE
[GENERAL] Shadekin get zapped by live wires while phased

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#241]
#### Brief description of the bug

Shadekin, while phased get zapped by live wires and take damage. They should not, as they're technically on another plane, same as their immunity to rain and weather.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/410a1ef46dc6a4e750df29a995edecd3b51797e6
