### ISSUE TITLE
[GENERAL] Singularity is stopped by walls and doesn't consume walls anymore

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#242]
#### Brief description of the bug

(Tested on Mr Clean) when making a singularity, they don't consume walls and can't go through walls anymore. Removing their blocking is fixed by giving them unstoppable, but they still don't erase walls

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/b4a2f9b43f6cf03ead7784cd8ab333f5ba59e2a9
