### ISSUE TITLE
Hallucination damage makes you scream in pain

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#25]
#### Brief description of the bug

Hallucination damage makes you scream in pain. While perhaps amusing, or "realistic" it's more annoying than anything, and causes unnecessary alarm when someone is simply going through drug withdrawals. (Which should also be made clear in body scanners)
The obfuscation of your HUD's health, slowdown, paincrit sounds, and blurry edge vision is already enough to hint you're in serious hal-pain, the scream is simply unnecessary

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/8fae3772ace6abcea1083364270a2375c6778458
