### ISSUE TITLE
✨Solution for forced movement while resting

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#257]
#### What you want to happen
 
While resting (pressing u), you an be forced to move from drug or hallucination effects. While wanting to laze and use drugs with the bois, or rp with an addiction, this becomes annoying quickly.
Ideally: Either a toggle in the IC tab as a verb to disable prone movement, or even just allow yourself to be prone/resting while buckled so you're not forced to sit up.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/0fe03e8a047aa2f450a8eba42502b376dfc31895
