### ISSUE TITLE
[GENERAL] Emotes and actions trigger runespeak sounds

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#258]
#### Brief description of the bug

Emotes and actions trigger runespeak sounds. They shouldn't, as they're physical actions being taken.
Sign language already has an exception for runespeak that can be borrowed.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/d8aef086d16e71e6f8c12dfdadf38bfb25f386da
