### ISSUE TITLE
✨More ghost features and fun

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#263]
#### Brief description of the feature

Ghosts the ability to flicker licks. (Clicking on the light flickers it, like knocking on a window)
Ghosts the ability to spin chairs... so scary~
Ghosts flushing toilets?
If a ghost crosses your turf, you get a shiver down your spine.

Jils trying to steal ghosts? "The jil grabs at the empty air!"
Oties bark and freak out at ghosts

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/2ba37194d4acdf922c4019d59a1f473a08f434e2
