### ISSUE TITLE
[GENERAL] Swoopies should be given electrical armor to not die on live wires

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#265]
#### Brief description of the bug

Swoopies often live in maintenance, but with the live wire "traps" this often ends poorly for them. Lets insulate their poor feeties.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/e1c8805ceb5d3f63780d017e601b5f83a75326a0
