### ISSUE TITLE
[GENERAL] Mobs lose AI permanently if they ever get player controlled.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#27]
#### Brief description of the bug

Mobs have their AI disabled while controlled by a player, this is normal. However, when a player releases control and is resleeved, takes control of another mob, or otherwise moves on, the mob never restores AI control, becoming braindead for eternity.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/660d619533b167311db135bfe710246857580e38
