### ISSUE TITLE
[GENERAL] Backup implants can still be acquired through Nanomed

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#28]
#### Brief description of the bug

Backup implants, and implanters, are against the feel, goal, and lore of the server and need to be removed from Nanomed. Should be checked if they are accessible through science as well, and likely removed from there. (Or at least flagged as contraband, needing some illegal research if people REALLY want the live update of their destruction.)

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/6bbc375c8fad6b5f1718359fa7bc6dddde3c40ca
