### ISSUE TITLE
[GENERAL] QM's should have bridge access (19?)

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#281]
#### Brief description of the bug

QM's should have access to the bridge and such along with other heads, and their radio's should have command access.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/f40e5a3145fd71b7f40bc1f3211d17d5473ca024

and

https://github.com/Willburd/CHOMPost21/commit/31e8a27b56d7d355afaeaf2be759d7c41dfd6570
