### ISSUE TITLE
[GENERAL] Vox bodies can't be grown in the special sleever

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#29]
#### Brief description of the bug

Vox bodies can't be grown in the clone pod located in the Voxlab. They should be able to be grown there, due to specialization of the equipment.
They also should not be given a mask and tank immediately on being resleeved, as the room's atmosphere is already phoron, and there's already spare phoron tanks and masks in the room that can be found and used.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/c552b559274b5d8b087c942f2f433675a2b5d160
