### ISSUE TITLE
✨Dorm late join spawnpoint?

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#294]
#### Brief description of the feature

Potentially the ability to set your spawnpoint to the dorms, spawning you in the hallway outside the dorms with a message of "[name] has clocked in from the dorms!"
No way to log out there, just a different implication for staying on the surface station overnight.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/6f63abaff5221a1611dcd497d6db36e6e5a3ff55
