### ISSUE TITLE
[Investigate] Buckle interactions with stairs is broken again

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#30]
#### Brief description of the bug

In some situations, pulling someone on a stretcher behind you, while going down stairs, will cause them to move prior to the stretcher, causing it to fall onto them and deal damage.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/fb20683e3830b84079b1636a13c3b3434f7d8ae7
