### ISSUE TITLE
[GENERAL] Fishing in the acid water

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#309]
#### Brief description of the bug

Currently you can fish in the acid waters of the map, in the river, puddles, and terraformer. This is unintentional and a flag missed after we moved to chomp.
Most fish likely can't survive the enzymatic waters and so fishing shouldn't pull free fish.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/8ad088cfee1fa5046b5da4d18f310cc773cbc912
