### ISSUE TITLE
[GENERAL] Mice & cockroaches (Simplemobs?) aren't being checked for enzyme immunity in water

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#325]
#### Brief description of the bug

Mice and cockroaches are immune to the river's acid, despite not being flagged as enzyme immune, and cockroaches can survive in space.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/4ba53b422cb290ea292b8fc33eeab579186a7c93

Pretty sure cockroaches in space is intended
