### ISSUE TITLE
✨Expanded mob list for tunnel spawns

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#326]
#### Brief description of the feature

Issue: The maintenance tunnels get quiet and repetitive after awhile, with the same basic mobs.
Solutions: Expanding the list of critters that can spawn at maint_pred locations (Maybe spider spawns? or a new landmark?) to enhance the variety of creatures in the maintenance tunnels, and increase the hazard.
A minor event for spawning small creatures at the maint_pred locations would help refresh the hazard throughout the round.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/f0318d39b7520db616576c0ce8362566771346d3
