### ISSUE TITLE
[GENERAL] Allow lockpicks to unlock locked fence gates

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#328]
#### Brief description of the bug

Allow obj/item/lockpick to unlock obj/structure/fence/door/locked.
Might as well give it SOME use outside of exploration unique events.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/c760635f93482ae00e90e72f7ee0d5fd19c938b3
