### ISSUE TITLE
[GENERAL] Fragmentation landmines & grenades don't explode

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#331]
#### Brief description of the bug

Fragmentation landmines ( /obj/item/mine/frag ) only summon the bullet projectiles, and do not deliver an explosion onto the turf or target. They completely lack the proc

Edit: Hand grenades also do not create a proper explosion, despite the code implying they should?

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/8881e804a38390cb884bfc6256a0d7028683749b
