### ISSUE TITLE
[GENERAL] Explosions should tear off limbs

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#332]
#### Brief description of the bug

Currently, limb tearing off can open happen with sharp weapon damage over a certain damage (as far as I know), causing limbing to happen so boringly rarely.
Explosions should have a very high chance of tearing off limbs, ripping off the limb if the limb takes over 20 damage from an explosion.

**Comment by Willburd** [comment]
Possibly resolve in https://github.com/Willburd/CHOMPost21/commit/d058c3df8592170ad0337b629091cb1865245f9a
