### ISSUE TITLE
[GENERAL] In-game VR tutorial needs rework/updating

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#333]
#### Brief description of the bug

the in-game VR tutorial for new players has fallen out of date with the chomp rebase and the many TGUI updates, and needs to be updated, possibly reworked and additional ones added.

**Comment by Willburd** [comment]
Mostly resolved in https://github.com/Willburd/CHOMPost21/commit/45e5e241c7857db4b3b6c054d8cf251c2042801b
