### ISSUE TITLE
[INVESTIGATE] Potential override issue with rigs and worn eyewear

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#338]
#### Brief description of the bug

Potential issue where rigs, specifically the engineering rig (obj/item/rig/ce) protect your eyes from welding as intended, but if you wear mesons or other goggles, they override and remove the welding protection from the rig's helmet.

**Comment by Willburd** [comment]
Intended mechanics, mesons and nightvisions give you flash weakness instead of protection, stacking with the helmet's welding protection and weakening it.
