### ISSUE TITLE
[GENERAL] Mobs getting stunned by fire?

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#339]
#### Brief description of the bug

Simplemobs, when set on fire, seem to pause and be unable to move or act. Unsure if this is them attempting to resist and put out the fire and just not announcing their action, or if something is breaking in their AI.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/ce26df44bd07e684f46d67541bbb7a4b1347f7d9
