### ISSUE TITLE
[GENERAL] Unable to put out fires on crewmembers

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#34]
#### Brief description of the bug

When attempting to pat out a fire on a crewmember that is on fire and dead, intent defaults to CPR, instead of patting out the flames, like it does when they are alive.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/73c560a09e41f1be8acb2fd0fc2d1f844a5df240
