### ISSUE TITLE
✨Bring back limb ashing

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#345]
#### What you want to happen
 
Limbs that take over a certain amount of burns in one go should be ashed. This used to primarily be a thing with hot electrical wires, where if you touched a wire super live, it would do a ton of burns and burn off the limb. Say, 30+ burns in one attack/proc would be enough to burn the limb off?

**Comment by Willburd** [comment]
Possibly resolve in https://github.com/Willburd/CHOMPost21/commit/d058c3df8592170ad0337b629091cb1865245f9a
