### ISSUE TITLE
[GENERAL] Fire extinguishers don't extinguish flaming crewmembers

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#35]
#### Brief description of the bug

When using a fire extinguisher on individuals that are on fire, presumably burning items, the foam/water from the fire extinguisher does not put out flames on burning crew/creatures

**Comment by Willburd** [comment]
Foam and sprayers apply water reagent to mobs, this code is working. There is just a limit to their capability. Reagent amount required to extinguish crew has been lowered, if still insufficient it can be buffed again.
