### ISSUE TITLE
✨Central Command "Panic Lockdown" admin button/verb

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#352]
#### Brief description of the feature

An admeme button that simulates panic mode... 
 - Activates certain blast doors (might need new subtypes) to shut and lock down.
 - Activates all the turrets to be active (need a new subtype)
    - Turrets announce "DROP YOUR WEAPONS AND GET ON THE GROUND"
    - They wait 2 seconds, if they fail, they just unleash hell. (Maybe firing bullets instead of lasers? Can check the CWIS turrets... /obj/machinery/porta_turret/industrial/military or obj/machinery/porta_turret/stationary/CIWS )
    - Possibly using the 15 round MG42 burst?
 - Possible adjusting lights, and/or setting Beepsky to 'attack anything not laying down' mode?

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/9d869c71e4e6b2b4efdabc61e5637edc6a25d1b8
