### ISSUE TITLE
[INVESTIGATE] Players gain medical radio channel after dying.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#357]
#### Brief description of the bug

For some reason, post death, people are getting access to medical coms. Their headsets don't allow it, nowhere near radios, to the point of having no headset and being in the corner of the map and still hearing it.
This only occurs after death, either being revived or resleeved. (Miiight be more common with resleeving? Seems almost every time in that case)

**Comment by Willburd** [comment]
testing made it clear that players were receiving medi comms even without a headset

**Comment by Willburd** [comment]
appears to be from some kind of object, but it is unclear which

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/5f883073708601a623602430a49bc276727f32ef
