### ISSUE TITLE
[GENERAL] Sliding on ice does not knock you prone

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#358]
#### Brief description of the bug

Stepping onto an ice turf (Tested on /turf/simulated/floor/outdoors/ice/muriki) does not knock you prone, but it does slide you across the ice properly, though perhaps too quickly? Should be an easy fix to make it act similar to spacelube

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/eb895a2d7627212e6df3237a4e3c2bf12440f04e
