### ISSUE TITLE
✨Need some way of countering ice

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#359]
#### Brief description of the feature

Ice is funny, but it should have some way of being countered.
Magboots, crawling, dragging, all have no effect on ice, you immediately slip and fly at mach speed across the ice.
Prone crawling and magboots at least should allow safe traversal across ice without sliding.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/eb895a2d7627212e6df3237a4e3c2bf12440f04e
