### ISSUE TITLE
✨Create a VR trainer for medical training.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#36]
#### Brief description of the feature

Make a course to run people through basic medical; medication creation, basic triage (Explain that it's in the PDA for future review), setting up cryo bays, how certain chems interact, surgery, ample monkey abuse, etc.

**Comment by Willburd** [comment]
Initial work started https://github.com/Willburd/CHOMPost21/commit/1ec52c9f90b383546b9b82ff9f5c696ccd24ed58
