### ISSUE TITLE
[GENERAL] Ice sliding speed is insane and should be slowed

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#360]
#### Brief description of the bug

when sliding across ice, you go at an insane speed. Possibly at max move speed. This should probably be slowed down significantly. Possibly to just a similar speed to spacelube? Or even slower perhaps?

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/eb895a2d7627212e6df3237a4e3c2bf12440f04e
