### ISSUE TITLE
[GENERAL] Snow slowdown might not exist

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#361]
#### Brief description of the bug

I vaguely recall snow slowing you down as you walked through it, as trudging through snow is definitely not as fast as walking on clean tiles. Testing in round (tested with turf/simulated/floor/snow/snow2/muriki) you are not any slower walking through snow, as you are on tiles.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/374ef1cc53c88a708bac2650a53e9449fa3a2792
