### ISSUE TITLE
✨Lowpop tweak: More viable code red

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#368]
#### Brief description of the feature

See how viable it is to add Code Red to the command and communication console (since the dumb thing already requires high level access) to make it more usable, especially for security forces on lowpop rounds where we might not have ONE head, much less two.
Potentially adding code delta into the keycard swipe?

**Comment by Willburd** [comment]
resolved in https://github.com/Willburd/CHOMPost21/commit/b2ea00a755607da8e14c5a9a44b092a7af61e858
