### ISSUE TITLE
[GENERAL] Transcore notification fixes

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#369]
#### Brief description of the bug

"Notify Transcore" verb is dumb, badly labeled, and misleading.
Currently, all it does is post a message in medical chat saying "(name) is past-due for a mind backup" This has issues with our station lore and is often ignored by medical.

### Solution to fix.
Let's add a new structure, perhaps similar to a flasher or threat detector that beeps if a ghost walks over it, map it in with a camera nearby. (So you can see WHO it is that died)
Pressing the "notify Transcore" (We should rename it to 'Notify medical of your death'), teleports you to this flasher, causing it to go off and causing you to find it, while posting a much more clear message in medical's coms, saying:
"The medical EMF Detector has received a new ping. Check for missing crew or unusual activity near the device."

We should also make it clear to players on resleeving, (add to the messages) they do NOT remember their time as a ghost, only remembering their last scan.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/05a24459103fd5118132cafe3a7dbe6e37228503
