### ISSUE TITLE
✨Bring back ghosts setting off threat detectors... but rarely.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#370]
#### Brief description of the feature

Let ghosts set off threat detectors again because that was funny as hell, but let's make it spam-resistant, by making it a rare chance.. maybe 10% chance if a ghost enters it, it gets set off.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/8c37cdd2524f6da7908e36f19772a0226d015268
