### ISSUE TITLE
✨Make bluespace bags FUNNY again

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#376]
#### The Problem

Bags of holding used to create singularities when merged (If you put one bluespace bag into another)
Now, they delete their contents and themselves, and make you feel bad... that's boring. However, making a singularity isn't an option, they're far too laggy and round-ending. That's not fun.

#### The Solution
What is fun... putting a bluespace bag into another causes a random effect, all FUN... In all situations, both bags and their contents are destroyed.
-Chance to just tear off your arm... or arms~ IE: it got caught in the bag and erased
-MASSIVE brute damage, just ripping you apart in a tiny singularity that instantly collapsed... but still ripped you apart.
-Nice chunky explosion~ Probably enough to instant gib you, the person next to you, and badly damage the room you were in. (Same size as a Telecube explosion)
-Chance to send you to redspace, cuz that's always Fun.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/21c99c8d0aef37910f362a1463340935ae82cd97
