### ISSUE TITLE
[GENERAL] Citalopram and other mood meds need to be re-buffed on duration

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#39]
#### Brief description of the bug

Medications such as citalopram for reduction of mind effects are anemic in duration and need to be buffed again, as they were buffed prior to port.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/324e6af091f30b58ddd7e2d427728b7ecaae2e9a
