### ISSUE TITLE
[GENERAL] Inconsistent medical loadout medkits

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#391]
#### Brief description of the bug

The medkit type you spawn with as a medic player is inconsistent. Nurses spawn with the advanced kit, EMT with the normal kit, etc.
They should be reconfigured so that either the medkits make sense to their type (Toxins for genetics, advanced for cmo/emo, basic for nurse/doctor, etc) or unified to where everyone just gets the advanced kit.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/6c0fba6f063042709a2b8c08e58bc3ff6ff9e3d6
