### ISSUE TITLE
✨Fire extinguisher cabinets should slowly refill fire extinguishers in them

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#392]
#### Brief description of the feature

Provides a nice way of refilling them, gives you incentive to place them back, and prevents any situations of "I don't know what to do with this... I'll just put it back" and then needing it later and finding the fire extinguisher is nearly, or entirely empty when you need it.
A slow fill is fine to avoid abuse.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/5e60e5eb04e24b82057dd531d49c0dcb8f68d2f1
