### ISSUE TITLE
✨Minor event to make ghosts visible

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#399]
#### Brief description of the feature

Potential usage of the code below:
A minor event that calls a random ghost and makes them visible to crew.

https://github.com/Willburd/CHOMPost21/blob/34ceddc5cc97dd05a4f2115ca265d4e6bb21956a/code/modules/mob/dead/observer/observer.dm#L848

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/04d2e1b33c62200fb298ed64a7dc5824f56e212b
