### ISSUE TITLE
✨Ability to turn OFF body camera monitors

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#401]
#### Brief description of the feature

Bodycameras can get very noisy as they relay the sound from every officer's bodycamera.. there should be a way to disable them.

**Comment by Willburd** [comment]
Altclicking bodycam monitor turns it off already. behavior already present.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/605c6fcd6e305c6c484da37f83b0febad0777510
