### ISSUE TITLE
[GENERAL] Slug trail RNGesus might be wrong

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#417]
#### Brief description of the bug

Slug trails are supposed to be a 50/50 chance to escape, but might be failing somewhere... perhaps an override or runtime?

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/0e3ce7bc2353382c55e1c9e0e388821ce8425602
