### ISSUE TITLE
[Investigate] Bad path malignant organs spawning.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#421]
#### Brief description of the bug

Something, most likely the malignant organ event, caused "Chem organ DO NOT USE THIS" to appear in a player. Player reports to have not added it to themselves with engineered organ growth.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/03f3770714dc8f5fa41c29b1a400ba2f5f5f22ed
