### ISSUE TITLE
[MAPPING] Alien event ship is fuckled

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#424]
#### Brief description of the bug

The alien ship is spawning without power, so the challenge door locks and turrets are worthless.
The area SHOULD have been flagged with fucking not requiring power, but I guess it's not... needs investigating to find out wtf is going on...

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/5d15e7abd2dffeef503502accfbf9784bd005937
