### ISSUE TITLE
[GENERAL] Night shift lighting doesn't respect station time

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#425]
#### Brief description of the bug

Night shift lighting SHOULD go off station time, which is randomized at round start, to set night shift from between 22:00-06:00, but it seems to be semi-random, or potentially going off the server's actual time?

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/588c7b34d9294d1008e3218109aaabaf485a6240
