### ISSUE TITLE
✨Refactor of cargo sell points. 

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#44]
#### Brief description of the feature

Cargo's job should in part be selling stuff from the station. Currently, crates are barely worth any points, and almost nothing else is.
This should be changed~

If cargo has the gameplay loop along with engineering of shipbreaking, and cargo goes maintenance scavenging, or raiding the connexes out in the yard, they should be encouraged to sell these, not just stockpile. As such, many illegal things should be worth quite a few points, leading to the question of 'sell it to the crew, keep it, or sell it for points for more illegal things'

Illegal crates that can be ordered should be made slightly more expensive to help avoid point loops, and further encourage selling things.

**Comment by Willburd** [comment]
Resolved with balancing of chemical refinery, awaiting icon selling
