### ISSUE TITLE
✨Cargo Custom Vending Machine.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#45]
#### Brief description of the feature

Cargo should be given a vending machine that can take just about anything, with prices custom set by a cargo tech, then locked for purchases, so cargo can sell to the crew, all the illegal things they find in maintenance. (or all the lights and light replacers before cargo decides to steal every light bulb on station)

**Comment by Willburd** [comment]
Replaced with https://github.com/Willburd/CHOMPost21/issues/63
