### ISSUE TITLE
✨Frayed Wire Trap

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#46]
#### Brief description of the feature

A small frayed wire that connects to the cable under it via directions, and electrocutes mobs walking over it as though they had attempted to open a trapped door, or touched an electrified grill. For additional funny traps in maintenance.

In addition: Due to the sparking and danger, frayed wires should act as an ignition source for igniting fires, same as a candle

**Comment by Willburd** [comment]
Current plan: make them a damage state to normal wires.
Ducttape or cut-replace them will repair and keep color.
adds an overlay for broken icon. add ex_act() code to break it(sharp items remove coating?)
Add all overlay directions to wires that are possible to remove the coating from

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/4602ec3cbb943e00f502c71d6d938e76bd265e08
