### ISSUE TITLE
[GENERAL] Spawn locations seem bugged for many jobs

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#49]
#### Brief description of the bug

Certain titles of the job seem unable to be placed with no visual error to the user when attempting  to round-start spawn, via the "ready" button. Confirmed: CMO, CE, Captain, RD.
They do not spawn you in your designated spawn location, but after round start you can un-ready and join as normal from the elevators with no issue.

#### Steps to reproduce
- Have a character with a known issue job
- Ready up to attempt to join
- Round starts, not spawned.
- Un-ready to refresh the menu.
- Join as normal with no errors all throughout.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/793b3cb5b9ccd9cf44657117cd9a5c9ae962c61d
