### ISSUE TITLE
Cleaning blood writing doesn't actually remove it from the tile's content

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#51]
#### Brief description of the bug

When using the ghost verb "Write in blood" to make a decal, you can only write 5 messages in blood, which is okay. But when cleaning the blood off, it doesn't clear the blood variable list of "contents" from the tile, meaning it'll still be at message cap, despite being cleaned off.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/312391e960b0c03ac7e239e53c736585526c55b6
