### ISSUE TITLE
Shadekin mobs are affected by environment when phased

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#53]
#### Brief description of the bug

The old simple_mob shadekin, when phased, will set of triggers such as landmines, beartraps, and maglev rails, quickly resulting in them getting obliterated. Seems to be fixed on carbon mob shadekin.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/48ea39dfd94868861b5d88770790d4b57c2a3328
