### ISSUE TITLE
[Critical] Emitters memory leak to levels capable of crashing a server during a normal round. 

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#56]
#### Brief description of the bug

Emitters have a memory leak where they're not deleting their references, which builds up. A tesla engine started mid-round causes an Out of Memory crash by round end.

**Comment by Willburd** [comment]
Upstream issue. bandaid in https://github.com/Willburd/CHOMPost21/commit/80519c8a2e32d11f3d1946f7f1afdf18612a824b
