### ISSUE TITLE
✨Claymores/tripwire landmines

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#58]
#### Brief description of the feature

Landmines that would function as a directional charge. Two step?
Idea being you place the primary charge facing a direction. It either detects motion in front of it, or is set off by some kind of on_step trigger with as a tripwire.
On detonation, it causes a small blast at its location (1-2 tile explosion?) followed by launching a projectile, such as a shotgun blast, in the direction its facing. Allowing for a long-range trap with minimal terrain damage, but plenty of anti-personnel capability.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/02064fcd2802ac3e43328c824b784bcab5025edb
