### ISSUE TITLE
✨Mice and Jils having a verb to squeeze under doors

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#59]
#### Brief description of the feature

Mice and Jils, being tiny little guys, should be able to squeeze and wiggle their way through closed doors, allowing them to escape secured areas when players join as vermin spawn in unfortunate areas, or get trapped by players.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/7a5992457dc02fb0ba2ad2569085ed9a601a300f
