### ISSUE TITLE
Floor painters can remove base spline, but not wooden spline

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#69]
#### Brief description of the bug

When using a floor painter set to 'remove decals' it can remove floor corner painting, as well as base type black splines, but wooden splines are unable to be removed or created via any means in-game currently.
Floor painter should be able to add, and remove them.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/6cee641b6ce33a8a2e3822d52679d5f547c06bae
