### ISSUE TITLE
✨Hookahs

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#71]
#### Brief description of the feature

Semi-realistic hookahs. A central structure that can be filled with water, and a reagent of choice. (Maybe requires to be lit? Realistically you use hot coals on the very top, but we lack hot coals or ways to heat them)
Hookahs should have a hose count (1-4?) set internally, or possibly added. Right clicking on the hookah allows you to take a hose much like the swoopie's "borrow hose" verbs. If enough people have taken a hose out, more people cannot take a hose. (IE: If the hookah has 4 hoses, and 4 people are holding one, a fifth person cannot take one)

With a hose in hand, clicking on yourself will take a draw from the hookah, adding the reagent to your bloodstream, and removing a small bit of the water from the basin. Allowing for group smoking of whatever hellish concoction cargo whipped up this time. (Or the chemist being cheeky and putting tricord in it)

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/7cd7b943c074ff028ea20f60177ae29144c1f0d9
