### ISSUE TITLE
[GENERAL] Hunger seems to be draining excessively quickly

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#76]
#### Brief description of the bug

Crew seem to be getting hungry significantly faster than before, which becomes suffering on teshari players.
I suspect this was changed because of Virgo players eating 20+ players with save weight on, then wondering why they become rolling blobs that never lose weight.

**Comment by Willburd** [comment]
Confirmed to be due to reagent generation in belly, won't fix.
