### ISSUE TITLE
Shadekin Job banned on everything

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#78]
#### Brief description of the bug

Color-eyed shadekin are job-banned on everything, as they are only allowed to off-map spawn with jobs we have cut and removed.
They should be allowed to spawn as entertainers (for journalists) and stowaways at least. They're already under strict whitelist, just... enforce the whitelist? A character should only be whitelisted for a single character and single position, deviation from that should remove the whitelist validation and/or cause job bans or more?

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/4a585c609764da46661aaf0f41afbece22aa8e7d
