### ISSUE TITLE
Leopardmander maws autotransfer and interactions start disabled.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#84]
#### Brief description of the bug

Leopardmander maws do not start with autotransfer, or interactions, despite being seemingly coded to do so. This renders them inescapable, and incapable of acting properly, as they swallow you to their maw, and then trap you there until you OOC escape (or they get newspapered)

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/a279cd3412de6f7a9204b5d13041b7dffc4f6054
