### ISSUE TITLE
Items don't interact with the world when dropped in a pred stomach.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#86]
#### Brief description of the bug

Items, such as grenades, do not interact with the world once dropped in a pred's stomach.
Tested with grenades: No explosion is caused, no damage is dealt to predator or prey, but projectiles are still spawned from the grenade and fired out from the centered location.

This should probably be fixed to either completely nullify the grenade, or cause some kind of damage. Even if just gibbing the pred with no collateral damage.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/20a46852f79fd78e4ce9070f703e86dc9a5f7d45
