### ISSUE TITLE
Pills dropped in a stomach do not administer their reagents to the pred.

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#88]
#### Brief description of the bug

Pills, such as Ickypak, when dropped in a stomach, even after being digested, do not apply their affects to the pred, not adding the reagent to the predator. This potentially includes trash eating whole pills, or being force-fed the whole pill.

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/4ace7ff9cc995821e7d58ec1e4c622e43e941636
