### ISSUE TITLE
Rec. yard ore gen not happening

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#91]
#### Brief description of the bug

Ore generation on the reclamation yard appears to not be occurring. Ores generating at the rec yard should be primarily high value ores with few artifacts, making it exceedingly valuable to mine there, where station-level oregen should be entirely low-level ores with many artifacts. (I believe high/low level ores are already defined in code)

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/b301364e21ae6ba982b580859989950248d36ed4
