### ISSUE TITLE
Leporazine does not respect species temperature

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#97]
#### Brief description of the bug

Leporazine only brings temperature to a "normal" 98.6F/37C, and does not respect species "normal" temperature, IE: teshari normal temperature being at 1C

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/c0693e014ea8778f9c3f7efaa71a4774b1c0ae4d
