### ISSUE TITLE
[MAPPING] Need an ignore_caves variant for Crystal walls

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#98]
#### Brief description of the bug

/turf/simulated/mineral/crystal lacks an ignore_cavegen variant. Used to not be a problem until Chomp mapchanges made it non-hierarchal. Crystal areas should not spawn caves. (Or ores but I'll take ores over caves)

**Comment by Willburd** [comment]
Resolved in https://github.com/Willburd/CHOMPost21/commit/c47c4f191334e5ef087f4eb10b4bfbb952ea55c3
